<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\Karyawan;
use App\Enums\StatusKaryawanEnum;
use App\Enums\JenisKelaminEnum;
use App\Enums\StatusPernikahanEnum;
use App\Enums\JenisKontrakEnum;

class KaryawanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $karyawans = [
            [
                'email' => 'ahmad.wijaya@company.com',
                'password' => Hash::make('password123'),
                'nik' => 'EMP001',
                'nip' => 'NIP001',
                'nama_lengkap' => 'Ahmad Wijaya',
                'nama_panggilan' => 'Ahmad',
                'jenis_kelamin' => JenisKelaminEnum::Laki,
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-05-15',
                'agama' => 'Islam',
                'status_pernikahan' => StatusPernikahanEnum::Married,
                'alamat_domisili' => 'Jl. Merdeka No. 123, Jakarta Pusat',
                'alamat_ktp' => 'Jl. Merdeka No. 123, Jakarta Pusat',
                'no_telepon' => '021-1234567',
                'no_hp' => '081234567890',
                'email_pribadi' => 'ahmad.wijaya.personal@gmail.com',
                'no_ktp' => '3171051505900001',
                'no_npwp' => '12.345.678.9-012.000',
                'no_bpjs_kesehatan' => '0001234567890',
                'no_bpjs_ketenagakerjaan' => '12345678901',
                'jabatan' => 'Senior Software Engineer',
                'departemen' => 'IT',
                'divisi' => 'Development',
                'unit_kerja' => 'Backend Team',
                'lokasi_kerja' => 'Jakarta Office',
                'tanggal_masuk' => '2020-01-15',
                'jenis_kontrak' => JenisKontrakEnum::Tetap,
                'status_karyawan' => StatusKaryawanEnum::Aktif,
                'level_jabatan' => 'Senior',
                'grade' => 'S2',
                'gaji_pokok' => 15000000.00,
                'tunjangan' => json_encode([
                    'transport' => 1000000,
                    'makan' => 750000,
                    'kesehatan' => 500000
                ]),
                'shift_kerja' => 'Regular',
                'kontak_darurat_nama' => 'Siti Wijaya',
                'kontak_darurat_hubungan' => 'Istri',
                'kontak_darurat_telepon' => '081234567891',
                'pendidikan_terakhir' => 'S1',
                'institusi_pendidikan' => 'Universitas Indonesia',
                'jurusan' => 'Teknik Informatika',
                'tahun_lulus' => 2012,
                'pengalaman_kerja' => '8 tahun pengalaman di bidang software development',
                'keahlian' => 'PHP, Laravel, JavaScript, MySQL, Docker',
                'sertifikasi' => 'AWS Certified Developer, Laravel Certified',
                'is_active' => true,
                'created_by' => 'System',
            ],
            [
                'email' => 'sari.indah@company.com',
                'password' => Hash::make('password123'),
                'nik' => 'EMP002',
                'nip' => 'NIP002',
                'nama_lengkap' => 'Sari Indah Permata',
                'nama_panggilan' => 'Sari',
                'jenis_kelamin' => JenisKelaminEnum::Perempuan,
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1992-08-22',
                'agama' => 'Islam',
                'status_pernikahan' => StatusPernikahanEnum::Single,
                'alamat_domisili' => 'Jl. Sudirman No. 456, Jakarta Selatan',
                'alamat_ktp' => 'Jl. Asia Afrika No. 789, Bandung',
                'no_telepon' => '021-2345678',
                'no_hp' => '081234567892',
                'email_pribadi' => 'sari.indah.personal@gmail.com',
                'no_ktp' => '3271086208920002',
                'no_npwp' => '23.456.789.0-123.000',
                'no_bpjs_kesehatan' => '0002345678901',
                'no_bpjs_ketenagakerjaan' => '23456789012',
                'jabatan' => 'HR Specialist',
                'departemen' => 'HRD',
                'divisi' => 'Human Resources',
                'unit_kerja' => 'Recruitment',
                'lokasi_kerja' => 'Jakarta Office',
                'tanggal_masuk' => '2021-03-01',
                'jenis_kontrak' => JenisKontrakEnum::Tetap,
                'status_karyawan' => StatusKaryawanEnum::Aktif,
                'level_jabatan' => 'Specialist',
                'grade' => 'S1',
                'gaji_pokok' => 12000000.00,
                'tunjangan' => json_encode([
                    'transport' => 800000,
                    'makan' => 600000,
                    'kesehatan' => 400000
                ]),
                'shift_kerja' => 'Regular',
                'kontak_darurat_nama' => 'Budi Permata',
                'kontak_darurat_hubungan' => 'Ayah',
                'kontak_darurat_telepon' => '081234567893',
                'pendidikan_terakhir' => 'S1',
                'institusi_pendidikan' => 'Universitas Padjadjaran',
                'jurusan' => 'Psikologi',
                'tahun_lulus' => 2014,
                'pengalaman_kerja' => '7 tahun di bidang HR dan recruitment',
                'keahlian' => 'Recruitment, Employee Relations, Training & Development',
                'sertifikasi' => 'SHRM-CP, PHR Certified',
                'is_active' => true,
                'created_by' => 'System',
            ],
            [
                'email' => 'budi.santoso@company.com',
                'password' => Hash::make('password123'),
                'nik' => 'EMP003',
                'nip' => 'NIP003',
                'nama_lengkap' => 'Budi Santoso',
                'nama_panggilan' => 'Budi',
                'jenis_kelamin' => JenisKelaminEnum::Laki,
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1988-12-10',
                'agama' => 'Kristen',
                'status_pernikahan' => StatusPernikahanEnum::Married,
                'alamat_domisili' => 'Jl. Gatot Subroto No. 789, Jakarta Timur',
                'alamat_ktp' => 'Jl. Gatot Subroto No. 789, Jakarta Timur',
                'no_telepon' => '021-3456789',
                'no_hp' => '081234567894',
                'email_pribadi' => 'budi.santoso.personal@gmail.com',
                'no_ktp' => '3175071012880003',
                'no_npwp' => '34.567.890.1-234.000',
                'no_bpjs_kesehatan' => '0003456789012',
                'no_bpjs_ketenagakerjaan' => '34567890123',
                'jabatan' => 'Finance Manager',
                'departemen' => 'Keuangan',
                'divisi' => 'Finance & Accounting',
                'unit_kerja' => 'Budget Planning',
                'lokasi_kerja' => 'Jakarta Office',
                'tanggal_masuk' => '2019-06-01',
                'jenis_kontrak' => JenisKontrakEnum::Tetap,
                'status_karyawan' => StatusKaryawanEnum::Aktif,
                'level_jabatan' => 'Manager',
                'grade' => 'M1',
                'gaji_pokok' => 20000000.00,
                'tunjangan' => json_encode([
                    'transport' => 1200000,
                    'makan' => 900000,
                    'kesehatan' => 600000,
                    'jabatan' => 2000000
                ]),
                'shift_kerja' => 'Regular',
                'kontak_darurat_nama' => 'Maya Santoso',
                'kontak_darurat_hubungan' => 'Istri',
                'kontak_darurat_telepon' => '081234567895',
                'pendidikan_terakhir' => 'S1',
                'institusi_pendidikan' => 'Universitas Airlangga',
                'jurusan' => 'Akuntansi',
                'tahun_lulus' => 2010,
                'pengalaman_kerja' => '12 tahun di bidang finance dan accounting',
                'keahlian' => 'Financial Planning, Budget Management, Tax Planning, SAP',
                'sertifikasi' => 'CPA, CFA Level II',
                'is_active' => true,
                'created_by' => 'System',
            ],
            [
                'email' => 'lisa.maharani@company.com',
                'password' => Hash::make('password123'),
                'nik' => 'EMP004',
                'nip' => 'NIP004',
                'nama_lengkap' => 'Lisa Maharani',
                'nama_panggilan' => 'Lisa',
                'jenis_kelamin' => JenisKelaminEnum::Perempuan,
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1995-03-18',
                'agama' => 'Islam',
                'status_pernikahan' => StatusPernikahanEnum::Single,
                'alamat_domisili' => 'Jl. Thamrin No. 321, Jakarta Pusat',
                'alamat_ktp' => 'Jl. Thamrin No. 321, Jakarta Pusat',
                'no_telepon' => '021-4567890',
                'no_hp' => '081234567896',
                'email_pribadi' => 'lisa.maharani.personal@gmail.com',
                'no_ktp' => '3171055803950004',
                'no_npwp' => '45.678.901.2-345.000',
                'no_bpjs_kesehatan' => '0004567890123',
                'no_bpjs_ketenagakerjaan' => '45678901234',
                'jabatan' => 'Junior Developer',
                'departemen' => 'IT',
                'divisi' => 'Development',
                'unit_kerja' => 'Frontend Team',
                'lokasi_kerja' => 'Jakarta Office',
                'tanggal_masuk' => '2023-01-15',
                'tanggal_kontrak_mulai' => '2023-01-15',
                'tanggal_kontrak_selesai' => '2024-01-14',
                'jenis_kontrak' => JenisKontrakEnum::Kontrak,
                'status_karyawan' => StatusKaryawanEnum::Aktif,
                'level_jabatan' => 'Junior',
                'grade' => 'J1',
                'gaji_pokok' => 8000000.00,
                'tunjangan' => json_encode([
                    'transport' => 600000,
                    'makan' => 500000,
                    'kesehatan' => 300000
                ]),
                'shift_kerja' => 'Regular',
                'kontak_darurat_nama' => 'Rina Maharani',
                'kontak_darurat_hubungan' => 'Ibu',
                'kontak_darurat_telepon' => '081234567897',
                'pendidikan_terakhir' => 'S1',
                'institusi_pendidikan' => 'Universitas Sumatera Utara',
                'jurusan' => 'Sistem Informasi',
                'tahun_lulus' => 2017,
                'pengalaman_kerja' => '5 tahun pengalaman frontend development',
                'keahlian' => 'HTML, CSS, JavaScript, React, Vue.js',
                'sertifikasi' => 'React Developer Certification',
                'is_active' => true,
                'created_by' => 'System',
            ],
            [
                'email' => 'doni.prasetyo@company.com',
                'password' => Hash::make('password123'),
                'nik' => 'EMP005',
                'nip' => 'NIP005',
                'nama_lengkap' => 'Doni Prasetyo',
                'nama_panggilan' => 'Doni',
                'jenis_kelamin' => JenisKelaminEnum::Laki,
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1993-07-25',
                'agama' => 'Islam',
                'status_pernikahan' => StatusPernikahanEnum::Single,
                'alamat_domisili' => 'Jl. Rasuna Said No. 654, Jakarta Selatan',
                'alamat_ktp' => 'Jl. Malioboro No. 123, Yogyakarta',
                'no_telepon' => '021-5678901',
                'no_hp' => '081234567898',
                'email_pribadi' => 'doni.prasetyo.personal@gmail.com',
                'no_ktp' => '3404072507930005',
                'no_npwp' => '56.789.012.3-456.000',
                'no_bpjs_kesehatan' => '0005678901234',
                'no_bpjs_ketenagakerjaan' => '56789012345',
                'jabatan' => 'Logistic Coordinator',
                'departemen' => 'Logistik',
                'divisi' => 'Supply Chain',
                'unit_kerja' => 'Procurement',
                'lokasi_kerja' => 'Jakarta Office',
                'tanggal_masuk' => '2022-08-01',
                'jenis_kontrak' => JenisKontrakEnum::Tetap,
                'status_karyawan' => StatusKaryawanEnum::Aktif,
                'level_jabatan' => 'Coordinator',
                'grade' => 'C1',
                'gaji_pokok' => 10000000.00,
                'tunjangan' => json_encode([
                    'transport' => 700000,
                    'makan' => 550000,
                    'kesehatan' => 350000
                ]),
                'shift_kerja' => 'Regular',
                'kontak_darurat_nama' => 'Sari Prasetyo',
                'kontak_darurat_hubungan' => 'Ibu',
                'kontak_darurat_telepon' => '081234567899',
                'pendidikan_terakhir' => 'S1',
                'institusi_pendidikan' => 'Universitas Gadjah Mada',
                'jurusan' => 'Manajemen Logistik',
                'tahun_lulus' => 2015,
                'pengalaman_kerja' => '6 tahun di bidang supply chain dan logistik',
                'keahlian' => 'Supply Chain Management, Procurement, Inventory Management',
                'sertifikasi' => 'CSCP, APICS Supply Chain Operations Reference',
                'is_active' => true,
                'created_by' => 'System',
            ],
        ];

        foreach ($karyawans as $karyawanData) {
            Karyawan::create($karyawanData);
        }

        $this->command->info('Karyawan seeder completed successfully.');
        $this->command->info('Created ' . count($karyawans) . ' karyawan records.');
        $this->command->info('Default password for all karyawan: password123');
    }
}